config/routes.rb
Rails.application.routes.draw do
  
  authenticated do
    root to: 'texts#index', as: :authenticated
  end
  
  root to: 'home#index'

  devise_for :users
  resources :users, only: [:update, :show]
  resources :texts
  resources :charges, only: [:new, :create]

end

app/models/collaborating.rb
class Collaborating < ActiveRecord::Base
  belongs_to :user
  belongs_to :text
end

app/models/text.rb
class Text < ActiveRecord::Base
  has_many :collaboratings
  has_many :users, through: :collaboratings
  mount_uploader :image, ImageUploader
  default_scope { order('created_at DESC') }
  scope :visible_to, -> (user) { user ? all : where(public: true)}

  def authors
    self.users.map {|user| user.name}.sort.join(", ")
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :collaboratings
  has_many :texts, through: :collaboratings
  mount_uploader :avatar, AvatarUploader
  validates :name, presence: true

  def premium?
    self.plan == "premium"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    texts_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :plan) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password, :plan, :avatar, :avatar_cache) }
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end

  def create
    @amount = 500

    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: @amount,
      description: "Textopedia Premium - #{current_user.email}",
      currency: 'usd'
    )

    flash[:notice] = "You are officially a member of the elite Premium club! Thanks for joining."
    current_user.update_attributes(plan: 'premium')
    redirect_to user_path(current_user)

    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @no_home_link = true
  end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  def index
    @texts = Text.visible_to(current_user).all
  end

  def new
    @text = Text.new
  end

  def create
    @text = Text.new(text_params)
    @text.users << current_user
    if @text.save
      flash[:notice] = "'#{@text.title}' was successfully created!"
      redirect_to @text
    else
      flash[:error] = "Sorry, there was a problem creating your text."
      render :new
    end
  end

  def show
    @text = Text.find(params[:id])
  end

  def edit
    @text = Text.find(params[:id])
  end

  def update
    @text = Text.find(params[:id])
    if @text.update_attributes(text_params)
      flash[:notice] = "'#{@text.title}' was successfully updated!"
      redirect_to @text
    else
      flash[:error] = "Sorry, there was a problem updating your text."
      render :edit
    end
  end

  def destroy
    @text = Text.find(params[:id])
    if @text.destroy
      flash[:notice] = "'#{@text.title}' was successfully deleted!"
      redirect_to texts_path
    else
      flash[:error] = "Sorry, there was a problem deleting your text."
      render :show
    end
  end

  private
  def text_params
    params.require(:text).permit(:title, :description, :public, :image, user_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @texts = @user.texts
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown(text)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render text).html_safe
  end
  
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/views/charges/_form.html.erb
<%= form_tag charges_path do %>
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-name="Premium Plan"
          data-description="Upgrade to a Premium plan"
          data-amount="500"></script>
<% end %>

app/views/charges/_form2.html.erb
<div data-no-turbolink>
<%= form_tag charges_path, id: 'chargeForm' do %>
  <%= hidden_field_tag 'stripeToken' %>
  <%= hidden_field_tag 'stripeEmail' %>
  <button id="customButton">Upgrade</button>

   <script>
   $(document).ready(function(){
        var handler = StripeCheckout.configure({
        key: 'pk_test_RTdrPkn2LzjLEMhEYAoxKGQn',
        token: function(token, args) {
              document.getElementById("stripeToken").value = token.id;                              
              document.getElementById("stripeEmail").value = token.email;
              document.getElementById("chargeForm").submit();
            }
          });

        document.getElementById('customButton').addEventListener('click', function(e) {
          // Open Checkout with further options
          handler.open({
            name: 'Premium Plan',
            description: 'Upgrade to the premium plan',
            amount: 500,
            currency: 'usd',
          });
          e.preventDefault();
        });
      })
    </script>
<% end %>
</div>

app/views/home/index.html.erb
<body class="home">
  <div class="home-head">text·o·pe·di·a (n)</div>
  <div class="home-text">Create, share, and read.</div>
  <br/>
  <div class="home-button">
    <button type="button" class="button"><%= link_to "Start Reading", texts_path %></button>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Textopedia</title>
  <link href='https://fonts.googleapis.com/css?family=Libre+Baskerville:400,700|Droid+Serif' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>  
  <%= stylesheet_link_tag "collaborators" %>
</head>
<body>

  <div class="container">
    <% if current_user %>
      <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <%= link_to "textopedia", root_path, class: 'navbar-brand left-nav-side' %>
          </div>

          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li>
                <%= link_to new_text_path, class: 'left-nav-side' do %>
                  <span class="glyphicon glyphicon-plus"></span>
                <% end %>
              </li>
            </ul>
          
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">

                <a href="" class="dropdown-toggle" data-toggle="dropdown">
                  <%= image_tag(current_user.avatar.thumb.url, class: 'circular') %>
                  <span class="caret"></span>
                </a>

                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "My Profile", current_user %></li>
                  <li><%= link_to "Edit Account", edit_user_registration_path %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    <% else %>
      <div class="visitor">
        <% unless @no_home_link %>
          <%= link_to "textopedia", texts_path, class: 'pull-left' %>
        <% end %>
        <div class="pull-right">
          <%= link_to "Sign In", new_user_session_path %> or <%= link_to "Sign Up", new_user_registration_path %>
        </div>
      </div>
    <% end %>

      <div id="flash-container">
        <% if flash[:notice] %>
            <div class="alert alert-notice"><%= flash[:notice] %></div>
        <% elsif flash[:error] %>
            <div class="alert alert-error"><%= flash[:error] %></div>
        <% elsif flash[:alert] %>
            <div class="alert alert-alert"><%= flash[:alert] %></div>
        <% end %>
      </div>


    <%= yield %>
  </div>
</body>
</html>

app/views/texts/_form.html.erb
<%= form_for text do |f| %>

  <% if text.image? %>
  <div>
    <%= image_tag(text.image.full.url) %>
  </div><br/>
  <% end %>

  <div>
    <%= f.label :title, class: 'form-label' %></br>
    <%= f.text_field :title, class: 'content', placeholder: 'Title' %>
  </div><br/>

  <div>
    <p><%= f.label :image, class: 'form-label' %></p>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
  </div></br>

  <div>
    <%= f.label :description, class: 'form-label' %></br>
    <div id="epiceditor">
      <%= f.text_area :description, class: 'content content-area', id: 'my-edit-area', placeholder: 'Enter content here' %>
    </div>
  </div>

  <% if current_user.premium? %>
  <div>
    <%= f.check_box :public %> <%= f.label :public, "Public", class: 'form-label' %>
  </div></br/>
  <% end %>

  <div><%= f.submit "Save", class: 'button submit-button' %></div>

<% end %>

app/views/texts/_text.html.erb
<div class="col-md-4">
  <% if text.image? %>
    <div><%= link_to image_tag(text.image.preview.url), text %></div>
  <% end %>
  
  <p>
    <div class="caption-title"><%= link_to text.title, text %></div>
    <p><small><%= text.authors %></small></p>
  </p>

</div>

app/views/texts/edit.html.erb
<h1>Edit Text</h1>
<br/>
<%= render partial: 'form', locals: { text: @text } %>

app/views/texts/index.html.erb
<h1>Texts</h1>

<% @texts.each_slice(3).to_a.each do |slice| %>
  <div class="row">
    <%= render partial: 'text', collection: slice %>
  </div>
<% end %>

app/views/texts/new.html.erb
<div class="row">
  <div class="col-md-8">
    <h1>New Text</h1>
    <%= render partial: 'form', locals: { text: @text } %>
  </div>
</div>

app/views/texts/show.html.erb
<h1><%= @text.title %></h1>
<%= @text.created_at.strftime("%b %d, %Y") %><br/>
<small>By <%= @text.authors %></small>

<% if current_user && @text.authors.include?(current_user.name) %>
  <div class="text-options">
    <button type="button" class="button submit-button"><%= link_to "Edit", edit_text_path %></button>
    <button type="button" class="button cancel-button"><%= link_to "Delete", @text, method: :delete, data: { confirm: "Are you sure you want to delete this text?" } %></button>

    <% if current_user.premium? %>
    <button type="button" class="button" data-toggle="modal" data-target="#myModal">Add Collaborators</button>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title" id="myModalLabel">Add Collaborators</h4>
          </div>

          <div class="modal-body">
          <%= form_for @text do |f| %>
            <%= f.collection_select :user_ids, User.all, :id, :name, {}, {class: 'chosen-select', multiple: true} %>
            <%= f.submit "Submit", class: "button submit-button" %>
          <% end %>
    
          </div>
          <div class="modal-footer">
            <button type="button" class="button cancel-button" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
<% end %>

<br/><br/>
<p><%= image_tag(@text.image.full.url) if @text.image? %></p>
<p><%= markdown @text.description %></p>

<script>
  $('.chosen-select').chosen({allow_single_deselect: true, no_results_text: 'No results matched', width: '300px'});
</script>

app/views/users/show.html.erb
<h1>Texts by <%= @user.name %></h1>
<% @texts.each_slice(3).to_a.each do |slice| %>
  <div class="row">
    <%= render partial: 'texts/text', collection: slice %>
  </div>
<% end %>